/** DOM reference collection for AI Chat. */
// Single source of truth: every HTML element id the app references.
// Adding a new element is a one-line change here — getRefs() and
// the Refs type are generated from this list automatically.
const ELEMENT_IDS = [
    "statusRow",
    "statusText",
    "modelToolbar",
    "btnRefresh",
    "btnProviders",
    "modelDropdownButton",
    "modelDropdown",
    "modelSearchInput",
    "modelOptionList",
    "modelSelect",
    "reasoningField",
    "reasoningSelect",
    "thinkingField",
    "thinkingSelect",
    "verbosityField",
    "verbositySelect",
    "claudeExtendedThinkingField",
    "claudeExtendedThinking",
    "claudeEffortField",
    "claudeEffortSelect",
    "providerDialog",
    "providerStatusRow",
    "providerStatusText",
    "providerList",
    "btnAddProvider",
    "btnCloseProviders",
    "providerForm",
    "providerTemplateField",
    "providerTemplate",
    "providerTemplateButton",
    "providerTemplateDropdown",
    "providerTemplateSearchInput",
    "providerTemplateOptionList",
    "providerId",
    "providerNameField",
    "providerName",
    "providerApiUrlField",
    "providerApiUrl",
    "providerApiKeyField",
    "providerApiKey",
    "providerCustomHeadersField",
    "providerCustomHeadersEnabled",
    "providerCustomHeadersInputField",
    "providerCustomHeaders",
    "providerModelFilterField",
    "providerFilterModels",
    "providerModelFilterRegexField",
    "providerModelFilterRegex",
  "codexAccountPanel",
  "codexAccountStatus",
  "codexAccountEmail",
  "codexAccountPlan",
    "codexAccountLimit",
    "codexAccountModels",
    "btnCodexRefresh",
    "claudeLoginRow",
    "btnClaudeLogin",
    "claudeAccountPanel",
    "claudeAccountEmail",
    "claudeAccountPlan",
    "claudeAccountModels",
    "btnClaudeRefresh",
    "btnClaudeSignOut",
    "claudeCodeLoginRow",
    "claudeCodeAccountPanel",
    "claudeCodeAccountStatus",
    "claudeCodeAccountPlan",
    "claudeCodeAccountLimit",
    "claudeCodeAccountModels",
    "btnClaudeCodeRefresh",
    "antigravityLoginRow",
    "antigravityAccountPanel",
    "antigravityAccountStatus",
    "antigravityProjectId",
    "antigravityEmail",
    "antigravityVersion",
    "antigravityPlan",
    "antigravityLimit",
    "antigravityModels",
    "btnAntigravityRefresh",
  "providerEditorTitle",
  "providerEnabled",
  "providerEnvWarning",
  "providerClaudeWarning",
  "providerAntigravityWarning",
  "providerActions",
    "btnCancelProvider",
    "btnNewSession",
    "navSessions",
    "resizerSidebar",
    "chatMessages",
    "resizerComposer",
    "formComposer",
    "inputComposer",
    "composerPreview",
    "btnSend",
  "btnCopyChat",
  "btnCopyRaw",
  "btnAuthor",
  "btnSource",
  "toggleMarkdown",
  "btnSettings",
    "settingsDialog",
    "btnCloseSettings",
    "settingsUpdatesCheckOnStartup",
  "btnCheckNow",
  "settingsUpdateResult",
  "settingsShowInfoBar",
    "settingsShowModelBar",
    "settingsTitleGenDropdownButton",
    "settingsTitleGenDropdown",
    "settingsTitleGenSearchInput",
    "settingsTitleGenOptionList",
    "settingsTitleGenSelect",
    "settingsVersion",
];
// Resolves all static DOM nodes used by the app.
export function getRefs() {
    const refs = {};
    for (const id of ELEMENT_IDS) {
        refs[id] = get(id);
    }
    return refs;
}
// Returns a typed element reference or fails fast during startup.
function get(id) {
    const element = document.getElementById(id);
    if (!element) {
        throw new Error(`Missing element #${id}`);
    }
    return element;
}
