/** Provider template list for quick OpenAI-compatible setup. */

export interface Template {
  name: string;
  apiUrl: string;
}

export const items: Template[] = [
  { name: "abacus", apiUrl: "https://routellm.abacus.ai/v1" },
  { name: "ai21", apiUrl: "https://api.ai21.com/studio/v1" },
  { name: "aihubmix", apiUrl: "https://aihubmix.com/v1" },
  { name: "aimlapi", apiUrl: "https://api.aimlapi.com/v1" },
  { name: "anyscale", apiUrl: "https://api.endpoints.anyscale.com/v1" },
  { name: "apipie", apiUrl: "https://apipie.ai/v1" },
  { name: "baichuan", apiUrl: "https://api.baichuan-ai.com/v1" },
  { name: "baiduqianfan", apiUrl: "https://qianfan.baidubce.com/v2" },
  { name: "cerebras", apiUrl: "https://api.cerebras.ai/v1" },
  { name: "chutes", apiUrl: "https://llm.chutes.ai/v1" },
  { name: "clarifai", apiUrl: "https://api.clarifai.com/v2/ext/openai/v1" },
  { name: "cohere", apiUrl: "https://api.cohere.com/compatibility/v1" },
  { name: "cometapi", apiUrl: "https://api.cometapi.com/v1" },
  { name: "cortecs", apiUrl: "https://api.cortecs.ai/v1" },
  { name: "dashscope", apiUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1" },
  { name: "deepinfra", apiUrl: "https://api.deepinfra.com/v1/openai" },
  { name: "deepseek", apiUrl: "https://api.deepseek.com/v1" },
  { name: "fastrouter", apiUrl: "https://go.fastrouter.ai/api/v1" },
  { name: "fireworks", apiUrl: "https://api.fireworks.ai/inference/v1" },
  { name: "friendli", apiUrl: "https://api.friendli.ai/serverless/v1" },
  { name: "giteeai", apiUrl: "https://ai.gitee.com/v1" },
  { name: "githubmodels", apiUrl: "https://models.github.ai/inference" },
  { name: "googlegemini", apiUrl: "https://generativelanguage.googleapis.com/v1beta/openai" },
  { name: "groq", apiUrl: "https://api.groq.com/openai/v1" },
  { name: "helicone", apiUrl: "https://oai.helicone.ai/v1" },
  { name: "hyperbolic", apiUrl: "https://api.hyperbolic.xyz/v1" },
  { name: "huggingface", apiUrl: "https://router.huggingface.co/v1" },
  { name: "iflytek", apiUrl: "https://spark-api-open.xf-yun.com/v1" },
  { name: "infiniai", apiUrl: "https://cloud.infini-ai.com/maas/v1" },
  { name: "inception", apiUrl: "https://api.inceptionlabs.ai/v1" },
  { name: "ionet", apiUrl: "https://api.intelligence.io.solutions/api/v1" },
  { name: "jina", apiUrl: "https://api.jina.ai/v1" },
  { name: "lambda", apiUrl: "https://api.lambda.ai/v1" },
  { name: "litellm", apiUrl: "http://localhost:4000/v1" },
  { name: "lmstudio", apiUrl: "http://localhost:1234/v1" },
  { name: "localai", apiUrl: "http://localhost:8080/v1" },
  { name: "minimax", apiUrl: "https://api.minimax.chat/v1" },
  { name: "mistral", apiUrl: "https://api.mistral.ai/v1" },
  { name: "mixedbread", apiUrl: "https://api.mixedbread.ai/v1" },
  { name: "moark", apiUrl: "https://moark.com/v1" },
  { name: "modelbest", apiUrl: "https://openapi.modelbest.cn/v1" },
  { name: "modelscope", apiUrl: "https://api-inference.modelscope.cn/v1" },
  { name: "moonshot", apiUrl: "https://api.moonshot.ai/v1" },
  { name: "nanogpt", apiUrl: "https://nano-gpt.com/api/v1" },
  { name: "nebius", apiUrl: "https://api.studio.nebius.ai/v1" },
  { name: "novitaai", apiUrl: "https://api.novita.ai/v3/openai" },
  { name: "nvidia", apiUrl: "https://integrate.api.nvidia.com/v1" },
  { name: "ollama", apiUrl: "http://localhost:11434/v1" },
  { name: "ollamacloud", apiUrl: "https://ollama.com/v1" },
  { name: "oneapi", apiUrl: "http://localhost:3000/v1" },
  { name: "openai", apiUrl: "https://api.openai.com/v1" },
  { name: "opencodezen", apiUrl: "https://opencode.ai/zen/v1" },
  { name: "openpipe", apiUrl: "https://app.openpipe.ai/api/v1" },
  { name: "openrouter", apiUrl: "https://openrouter.ai/api/v1" },
  { name: "ovhcloud", apiUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1" },
  { name: "parasail", apiUrl: "https://api.parasail.io/v1" },
  { name: "perplexity", apiUrl: "https://api.perplexity.ai" },
  { name: "poe", apiUrl: "https://api.poe.com/v1" },
  { name: "portkey", apiUrl: "https://api.portkey.ai/v1" },
  { name: "reka", apiUrl: "https://api.reka.ai/v1" },
  { name: "replicate", apiUrl: "https://api.replicate.com/v1" },
  { name: "requesty", apiUrl: "https://router.requesty.ai/v1" },
  { name: "sambanova", apiUrl: "https://api.sambanova.ai/v1" },
  { name: "sensenova", apiUrl: "https://api.sensenova.cn/compatible-mode/v1" },
  { name: "sglang", apiUrl: "http://localhost:30000/v1" },
  { name: "siliconflow", apiUrl: "https://api.siliconflow.cn/v1" },
  { name: "stepfun", apiUrl: "https://api.stepfun.com/v1" },
  { name: "synthetic", apiUrl: "https://api.synthetic.new/v1" },
  { name: "tabbyapi", apiUrl: "http://localhost:5000/v1" },
  { name: "tencentlkeap", apiUrl: "https://api.lkeap.cloud.tencent.com/v1" },
  { name: "together", apiUrl: "https://api.together.xyz/v1" },
  { name: "unify", apiUrl: "https://api.unify.ai/v0" },
  { name: "upstage", apiUrl: "https://api.upstage.ai/v1" },
  { name: "vercelaigateway", apiUrl: "https://ai-gateway.vercel.sh/v1" },
  { name: "vllm", apiUrl: "http://localhost:8000/v1" },
  { name: "volcengineark", apiUrl: "https://ark.cn-beijing.volces.com/api/v3" },
  { name: "voyage", apiUrl: "https://api.voyageai.com/v1" },
  { name: "xai", apiUrl: "https://api.x.ai/v1" },
  { name: "xinference", apiUrl: "http://localhost:9997/v1" },
  { name: "yi", apiUrl: "https://api.lingyiwanwu.com/v1" },
  { name: "zenmux", apiUrl: "https://zenmux.ai/api/v1" },
  { name: "zhipu", apiUrl: "https://open.bigmodel.cn/api/paas/v4" },
];

// Finds the first template matching a stored API URL.
export function byApiUrl(apiUrl: string): Template | undefined {
  const normalized = apiUrl.trim().replace(/\/+$/, "");
  return items.find((item) => item.apiUrl.replace(/\/+$/, "") === normalized);
}
