/** Enumerates every IPC channel exposed by AI Chat. */

export enum IpcChannel {
  AppBootstrap = 'app:bootstrap',
  SettingsSave = 'settings:save',
  ConversationCreate = 'conversation:create',
  ConversationGet = 'conversation:get',
  ConversationSave = 'conversation:save',
  ConversationRename = 'conversation:rename',
  ConversationDelete = 'conversation:delete',
  ConversationDeleteAll = 'conversation:delete-all',
  ProviderSave = 'provider:save',
  ProviderEditData = 'provider:edit-data',
  ProviderCatalogFetch = 'provider:catalog-fetch',
  ProviderAuthStart = 'provider:auth-start',
  ProviderAuthLogout = 'provider:auth-logout',
  ProviderAuthStatus = 'provider:auth-status',
  ProviderUsageFetch = 'provider:usage-fetch',
  ProviderEnabledSet = 'provider:enabled-set',
  ProviderOrderSet = 'provider:order-set',
  ProviderDelete = 'provider:delete',
  ModelFavoriteSet = 'model:favorite-set',
  ModelLastUsedSet = 'model:last-used-set',
  ModelQuickSet = 'model:quick-set',
  TitleGenerationEnabledSet = 'model:title-generation-enabled-set',
  ChatStart = 'chat:start',
  ChatStop = 'chat:stop',
  ChatStream = 'event:chat-stream',
  AttachmentsSelect = 'attachments:select',
  WindowAlwaysOnTop = 'window:always-on-top',
  WindowMinimize = 'window:minimize',
  WindowToggleMaximize = 'window:toggle-maximize',
  WindowClose = 'window:close',
  WindowIsMaximized = 'window:is-maximized',
  ThemeSet = 'theme:set',
  ShellOpenExternal = 'shell:open-external',
  LogsOpenDirectory = 'logs:open-directory',
  LogWrite = 'logs:write',
  UpdatesCheck = 'updates:check',
  UpdatesInstall = 'updates:install',
  UpdateState = 'event:update-state',
  WindowMaximizedChanged = 'event:window-maximized-changed',
  SettingsOpenRequested = 'event:settings-open-requested',
  FileSave = 'file:save',
}
